;; The AFSTN grammar, originally from file AFSTN (not GR1 !!)
;; But with many modifications.
;; This code populates the property list with it
;; (note, format is different from that in GR1)
(mapcar #'(lambda (x) (PUTPROP (CAR x) (CDR x) !GR))
        '(
          (S	(FIRS SNT1) (INF3 V0) V0)
          (V0	(VOICE V1))
          (SNT1	(LEX SNT2))
          (SNT2   (SECS T))
          (V1 	(FORM V2))
          (V2   (MODAL V3) V3)
          (V3	(TENSE V4))
           (V4  	(MOOD T))
          (COND   (CNDIT INDIC))
          (INTERROG (IVT INDIC))
          (SUBJUNC INDIC)
           (INDIC  (VS1 SBJ) SBJ)
           ;; JCM: below I added a direct transition to PRED
           ;; To support generating a verb clause without subject
           (SBJ  (SUBJ PRED) (GSBJ PRED) PRED)
           (PRED (MAN PRED1) PRED1)
          (PRED1	(NGT VP0) VP0)
          (VP0	(VS VP1))
          (VP1	(PART1 VP2) VP2)
          (VP2	(OBJ2 VP3) VP3)
          (VP3	(PP1 VP4) VP4)
          (VP4	(P_ADJ VP5) VP5)
          (VP5	(LOC VP6) VP6)
          (VP6    (OBJ VP7) VP7)
          (VP7	(PART2 VP8) VP8)
           (VP8	(IOBJ VP9) VP9)
           ;; JCM added GOBJ to the below
          (VP9	(INF VP10) (INF2 VP10)(S2 VP10)(S3 VP10)(SPRG VP10)(PRSNT VP10) (GOBJ VP10) VP10)
          (VP10	(INST T)(INST2 T))
          (INST2  S)
          (SPRG   S)
          (INF	S)
          (INF2   S)
          (S2	S)
          (FIRS	S)
           (SECS	S)
          (GSBJ	S)
          (PRSNT S)
           (GOBJ S) ;; JCM new addition
          (PP1	PNP)
          (INST	PNP)
          (IOBJ	PNP)
          (LOC	PNP)
          (PNP	(PREP PNP1))
          (PNP1	(POBJ T))
          (SUBJ	NP)
          (OBJ	NP)
          (POBJ	NP)
          (OBJ2   NP)
          (NP	(PRON NP3)(POSS NP1)(DET NP1) NP1)
          (NP1	(QUANT NP2) NP2)
          (NP2    (NBR NP3))
          (NP3	(NS NP4))
           (NP4	(PP1 NP5) NP5) ;; JCM added PP1 e.g. "cause of death"
           (NP5 (INF2 T) T)
;;           (NP5 (INF2 NP6) NP6);; JCM new addition, e.g. "inability to breathe"
           ;; could the PP1 and INF2 ever both occur? Don't think so
;;           (NP6 (EMBED NP7)) ;; JCM added for embedding clauses
;;           (NP7 (ES T)) ;; Prints "Embed string", result from embedding
          (POSS	(PRON NP3) (DET NP1) NP1)
          (P_ADJ  MOD)
          (MOD	(DEG MOD1))
          (MOD1	 (MS T))
          )
        )
